### ISSUE TITLE
enable jpeg support

### ISSUE THREAD

**Issue by tacman** [tangramor/nginx-php8-fpm#4]
Thanks for making this available.  Can you change the gd support so that it includes jpeg?

```bash
php -r "echo sprintf(\"JPEG SUPPORT? %s\n\", gd_info()['JPEG Support'] ? 'yes': 'no')  ;"
```

right now returns 'no', but jpeg is soooo common that I think it'd be great to include.

Also, adding the 'exif' extension would be nice, since that's so commonly used with jpeg files.

**Comment by tangramor** [comment]
OK, I will try in next version

**Comment by tangramor** [comment]
This feature is suppoted since php8.2.8_node20.5.0
