### ISSUE TITLE
How to solve “ImageMagick or GD is required”

### ISSUE THREAD

**Issue by anantsaraswat** [tangramor/nginx-php8-fpm#5]
Hi There, 

We are using the official Docker image from your Docker Hub page and recently discovered that the Imagify plugin is not working. It reports that there's no Imagick (ImageMagick) or GD for image resizing. Would it be possible to add these to your official image?

Many thanks,
Anant

**Comment by anantsaraswat** [comment]
https://imagify.io/documentation/solve-imagemagick-gd-required/

**Comment by tangramor** [comment]
GD is officially supported in the image. If you want install imagick module, you may refer to "Add extra PHP modules" section in the ReadMe.

**Comment by tangramor** [comment]
OK, I added imagick module in php8.3.6_node22.1.0 and php8.3.6_withoutNodejs builds.
