### ISSUE TITLE
Integrate Brotli

### ISSUE THREAD

**Issue by te-deum** [tangramor/nginx-php8-fpm#6]
Hello,

I would like to know if you consider adding _brotli_ into your image ?

Thank you.

**Comment by tangramor** [comment]
maybe next month.

**Comment by tangramor** [comment]
added

**Comment by te-deum** [comment]
First of all, thank you for considering this request.

Unfortunately you've only added Brotli for PHP but not for NGinx. As a result, we can't enjoy the benefits of Brotli directly on the NGinx server. This would be a definite advantage for server performance.

Do you think it will be possible to add Brotli modules to the NGinx server (ngx_http_brotli_filter_module and ngx_http_brotli_static_module)?

Thanks a lot.
